export const defaultStatusOptions = [
  "Wishlist",
  "OA - Online Assessment",
  "Applying",
  "Applied",
  "Waiting Referral",
  "No Response",
  "Ghosted",
  "Phone Screen",
  "Coding Challenge",
  "Take-Home Assignment",
  "Onsite",
  "Behavioral",
  "Interview Scheduled",
  "Interview Done",
  "Offer",
  "Rejected",
  "Accepted",
  "Archived",
];
