export const defaultStatusOptions = [
  "Wishlist",
  "OA - Online Assessment",
  "Applying",
  "Applied",
  "Waiting Referral",
  "No Response",
  "Ghosted",
  "Phone Screen",
  "Coding Challenge",
  "Take-Home Assignment",
  "Onsite",
  "Behavioral",
  "Interview Scheduled",
  "Interview Done",
  "Offer",
  "Rejected",
  "Accepted",
  "Archived",
];

export const columns = [
  "userId",
  "id",
  "isArchived",
  "isRemote",
  "mapLocation",
  "wasReferred",
  "referredBy",
  "companyId",
  "companyName",
  "companyInfo",
  "jobTitle",
  "jobLocation",
  "link",
  "applylink",
  "jobDescription",
  "status",
  "waitingFor",
  "timeline",
  "statusOptions",
  "resumeUsed",
  "motivationalLetter",
  "notes",
  "createdAt",
  "updatedAt",
  "interestLevel",
  "nextInterviewDate",
  "postedDate",
  "applicationDeadline",
  "salaryDetails",
  "appliedFrom",
  "heardAboutFrom",
  "todos",
];
